services:
  rory-client-0:
    image: shanelreyes/rory:client
    container_name: rory-client-0
    hostname: rory-client-0
    ports:
      - 3000:3000
    environment:
      - NODE_ID=rory-client-0
      - NODE_PORT=3000
      - NODE_IP_ADDR=rory-client-0
      - SERVER_IP_ADDR=0.0.0.0
      - RORY_MANAGER_IP_ADDR=rory-manager-0
      - RORY_MANAGER_PORT=6000
      - LOGGER_NAME=rory-client-0
      - MAX_ITERATIONS=10
      - MAX_THREADS=3
      - NUM_CHUNKS=4
      - MAX_WORKERS=4
      - XOLO_ENABLE=0
      - DEBUG =0
      - RELOAD=0
      - LIU_ROUND=1
      - TESTING=0
      - M=3
      - MICTLANX_PEERS=mictlanx-peer-0:mictlanx-peer-0:7000 mictlanx-peer-1:mictlanx-peer-1:7001
      - CUSTOM_PYTHON_PATH=/app
      - SOURCE_PATH=/rory/source
      - SINK_PATH=/rory/sink
      - LOG_PATH=/rory/log
    volumes:
      - /rory/rory-client-0/source:/rory/source
      - /rory/rory-client-0/sink:/rory/sink
      - /rory/rory-client-0/log:/rory/log
    networks:
      - mictlanx

networks:
  mictlanx: 
    external: true
