services:
  rory-client-0:
    image: ${RORY_IMAGE:-rory:client}
    container_name: rory-client-0
    hostname: rory-client-0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    # env_file:""
    environment:
      - RORY_DEBUG=${RORY_DEBUG:-0}
      - NODE_ID=rory-client-0
      - NODE_PORT=3000
      - NODE_IP_ADDR=rory-client-0
      - RORY_MANAGER_IP_ADDR=rory-manager-0
      - RORY_MANAGER_PORT=6000
      - RELOAD=0
      - LIU_ROUND=1
      - SERVER_IP_ADDR=0.0.0.0
      - NUM_CHUNKS=4
      - MAX_WORKERS=4
      - WORKER_TIMEOUT=300
      - SOURCE_PATH=/rory/source
      - SINK_PATH=/rory/sink
      - LOG_PATH=/rory/log
      - LOGGER_NAME=rory-client-0
      - MAX_ITERATIONS=10
      - TESTING=0
      - LIU_SECURITY_LEVEL=128
      - MICTLANX_TIMEOUT=120
      - MICTLANX_API_VERSION=3
      - MICTLANX_EXPIRES_IN=15d 
      - MICTLANX_PEERS=mictlanx-peer-0:mictlanx-peer-0:7000 mictlanx-peer-1:mictlanx-peer-1:7001
      - MICTLANX_DEBUG=0
      - MICTLANX_DAEMON=1
      - MICTLANX_SHOW_METRICS=0
      - MICTLANX_DISABLED_LOG=0
      - MICTLANX_MAX_WORKERS=4
      - MICTLANX_CLIENT_LB_ALGORITHM=2CHOICES_UF
    volumes:
      - /rory/rory-client-0/source:/rory/source
      - /rory/rory-client-0/sink:/rory/sink
      - /rory/rory-client-0/log:/rory/log
      - /rory/rory-client-0/mictlanx:/rory/mictlanx
      - /rory/rory-client-0/keys:/rory/keys
    networks:
      - mictlanx

networks:
  mictlanx: 
    external: true
