services:
  rory-client-0:
    image: shanelreyes/rory:client
    container_name: rory-client-0
    hostname: rory-client-0
    ports:
      - 3000:3000
    environment:
      - NODE_ID=rory-client-0
      - NODE_PORT=3000
      - NODE_IP_ADDR=rory-client-0
      - SERVER_IP_ADDR=0.0.0.0
      - RORY_MANAGER_IP_ADDR=rory-manager-0
      - RORY_MANAGER_PORT=6000
      - SINK_PATH=/rory/rory-client-0/sink
      - SOURCE_PATH=/rory/rory-client-0/source
      - LOG_PATH=/rory/rory-client-0/log
      - LOGGER_NAME=rory-client-0
      - MAX_ITERATIONS=10
      - MAX_WORKERS=1
      - DEBUG =0
      - RELOAD=0
      - LIU_ROUND=1
      - TESTING=0
      - M=3
      - MICTLANX_APP_ID=rory_HmsDacZ7RjkCNuDEKvej8ftpxDz2dcNF
      - MICTLANX_CLIENT_ID=rory-client-0
      - MICTLANX_SECRET=t0p53cr3T#
      - MICTLANX_PROXY_IP_ADDR=mictlanx-proxy-0
      - MICTLANX_PROXY_PORT=8080
      - MICTLANX_XOLO_IP_ADDR=mictlanx-xolo-0
      - MICTLANX_XOLO_PORT=10000
      - MICTLANX_REPLICA_MANAGER_IP_ADDR=mictlanx-rm-0
      - MICTLANX_REPLICA_MANAGER_PORT=20001
      - MICTLANX_API_VERSION=3
      - MICTLANX_EXPIRES_IN=15d
    volumes:
      - /rory/rory-client-0:/rory/rory-client-0
    networks:
      - mictlanx

networks:
  mictlanx: 
    external: true
