#!/bin/bash
readonly BASE_PATH=${1:-/home/sreyes/rory}
readonly MANAGER_IMAGE_TAG=${2:-manager}
readonly DATAOWNER_IMAGE_TAG=${3:-dataowner}
readonly WORKER_IMAGE_TAG=${4:-worker}
readonly EXPERIMENT_RUNNER_IMAGE_TAG=${5:-experiment-runner}

./build_all.sh $BASE_PATH $MANAGER_IMAGE_TAG $DATAOWNER_IMAGE_TAG $WORKER_IMAGE_TAG $EXPERIMENT_RUNNER_IMAGE_TAG
./push_all.sh $MANAGER_IMAGE_TAG $DATAOWNER_IMAGE_TAG $WORKER_IMAGE_TAG $EXPERIMENT_RUNNER_IMAGE_TAG

