services:
  rory-client-0:
    image: shanelreyes/rory:client
    container_name: rory-client-0
    hostname: rory-client-0
    ports:
      - 3000:3000
    environment:
      - RORY_DEBUG=0
      - NODE_ID=rory-client-0
      - NODE_IP_ADDR=rory-client-0
      - NODE_PORT=3000
      - SERVER_IP_ADDR=0.0.0.0
      - RORY_MANAGER_IP_ADDR=rory-manager-0
      - RORY_MANAGER_PORT=6000
      - NUM_CHUNKS=2
      - MAX_WORKERS=2
      - WORKER_TIMEOUT=300
      - SOURCE_PATH=/rory/source
      - SINK_PATH=/rory/sink
      - LOG_PATH=/rory/log
      - LOGGER_NAME=rory-client-0
      - MAX_ITERATIONS=10
      - M=3
      - RELOAD=0
      - LIU_ROUND=1
      - TESTING=0
      - MICTLANX_CLIENT_ID=rory-client-0
      - MICTLANX_TIMEOUT=300
      - MICTLANX_API_VERSION=3
      - MICTLANX_PEERS=mictlanx-peer-0:mictlanx-peer-0:7000 mictlanx-peer-1:mictlanx-peer-1:7001 mictlanx-peer-2:mictlanx-peer-2:7002
      - MICTLANX_DEBUG=0
      - MICTLANX_DAEMON=1
      - MICTLANX_SHOW_METRICS=0
      - MICTLANX_DISABLED_LOG=1
      - MICTLANX_MAX_WORKERS=4
      - MICTLANX_CLIENT_LB_ALGORITHM=2CHOICES_UF
      - MICTLANX_BUCKET_ID=rory
      - MICTLANX_OUTPUT_PATH=/rory/mictlanx
    volumes:
      - /rory/rory-client-0/source:/rory/source
      - /rory/rory-client-0/sink:/rory/sink
      - /rory/rory-client-0/log:/rory/log
      - /rory/rory-client-0/mictlanx:/rory/mictlanx
    networks:
      - mictlanx

  rory-manager-0:
    image: shanelreyes/rory:manager
    container_name: rory-manager-0
    hostname: rory-manager-0
    ports:
      - 6000:6000
    environment:
      - RORY_DEBUG=0
      - NODE_ID=rory-manager-0
      - NODE_IP_ADDR=rory-manager-0
      - NODE_PORT=6000
      - SERVER_IP_ADDR=0.0.0.0
      - NODE_PREFIX=rory-worker-
      - INIT_WORKERS=2
      - WORKER_INIT_PORT=9000
      - DOCKER_IMAGE_NAME=shanelreyes/rory
      - DOCKER_IMAGE_TAG=worker
      - DOCKER_NETWORK_ID=mictlanx
      - RELOAD=0
      - TESTING=0
      - MAX_RETRIES=10
      - LOAD_BALANCING=0
      - XOLO_ENABLE=0
      - WORKER_MAX_THREADS=2
      - WORKER_MEMORY=1000000000
      - WORKER_CPU=2
      - WORKER_TIMEOUT=300
      - SWARM_NODES=2,3,4,8
      - SOURCE_PATH=/rory/source
      - SINK_PATH=/rory/sink
      - LOG_PATH=/rory/log
      - MICTLANX_SUMMONER_IP_ADDR=mictlanx-summoner-0
      - MICTLANX_SUMMONER_PORT=15000
      - MICTLANX_SUMMONER_MODE=docker
      - MICTLANX_API_VERSION=3
      - MICTLANX_CLIENT_ID=rory-manager-0
      - MICTLANX_PEERS=mictlanx-peer-0:mictlanx-peer-0:7000 mictlanx-peer-1:mictlanx-peer-1:7001 mictlanx-peer-2:mictlanx-peer-2:7002
      - MICTLANX_TIMEOUT=300
      - MICTLANX_CLIENT_LB_ALGORITHM=2CHOICES_UF
      - MICTLANX_MAX_WORKERS=4
      - MICTLANX_DEBUG=0
      - MICTLANX_DAEMON=1
      - MICTLANX_SHOW_METRICS=0
      - MICTLANX_DISABLED_LOG=1
    volumes:
      - /rory/rory-manager-0/source:/rory/source
      - /rory/rory-manager-0/sink:/rory/sink
      - /rory/rory-manager-0/log:/rory/log
    networks:
      - mictlanx
networks:
  mictlanx:
    external: true
