version: "3.8"
services:
  mictlanx-xolo-0:
    image: nachocode/mictlanx:xolo
    container_name: mictlanx-xolo-0
    hostname: mictlanx-xolo-0
    ports:
      - 10000:10000
    environment:
      - NODE_ID=mictlanx-xolo-0
      - NODE_PORT=10000
      - SERVER_IP_ADDRESS=0.0.0.0
      - IP_ADDRESS=mictlanx-xolo-0
      - GOD_SECRET=te0imDRjzcA2lnRfwWzxu47NyVFq7xU/XWK/l7bPHPo=
    volumes:
      - /mictlanx/mictlanx-xolo-0:/mictlanx/mictlanx-xolo-0
    networks:
      - mictlanx

  mictlanx-proxy-0:
    image: nachocode/mictlanx:proxy
    container_name: mictlanx-proxy-0
    hostname: mictlanx-proxy-0
    ports:
      - 8080:8080
    environment:
      - NODE_ID=mictlanx-proxy-0
      - NODE_PORT=8080
      - SERVER_IP_ADDRESS=0.0.0.0
      - IP_ADDRESS=mictlanx-proxy-0
      - XOLO_IP_ADDR=mictlanx-xolo-0
      - XOLO_PORT=10000
      - LOAD_BALANCING_ALGORITHM=ROUND_ROBIN
    volumes:
      - /mictlanx/mictlanx-proxy-0:/mictlanx/mictlanx-proxy-0
    networks:
      - mictlanx
    depends_on:
      - mictlanx-xolo-0

  mictlanx-rm-0:
    image: nachocode/mictlanx:rm
    container_name: mictlanx-rm-0
    hostname: mictlanx-rm-0
    ports:
      - 20001:20001
    environment:
      - NODE_ID=mictlanx-rm-0
      - NODE_PORT=20001
      - IP_ADDRESS=mictlanx-rm-0
      - SERVER_IP_ADDRESS=0.0.0.0
      - XOLO_IP_ADDR=mictlanx-xolo-0
      - XOLO_PORT=10000
      - PROXY_IP_ADDR=mictlanx-proxy-0
      - PROXY_PORT=8080
      - LOAD_BALANCING_ALGORITHM=ROUND_ROBIN
    volumes:
      - /mictlanx/mictlanx-rm-0:/mictlanx/mictlanx-rm-0
    networks:
      - mictlanx
    depends_on:
      - mictlanx-xolo-0
      - mictlanx-proxy-0

  mictlanx-sn-0:
    image: nachocode/mictlanx:sn
    container_name: mictlanx-sn-0
    hostname: mictlanx-sn-0
    ports:
      - 7000:7000
    environment:
      - NODE_ID=mictlanx-sn-0
      - NODE_PORT=7000
      - IP_ADDRESS=mictlanx-sn-0
      - SERVER_IP_ADDRESS=0.0.0.0
      - XOLO_IP_ADDR=mictlanx-xolo-0
      - XOLO_PORT=10000
      - REPLICA_MANAGER_IP_ADDR=mictlanx-rm-0
      - REPLICA_MANAGER_PORT=20001
      - NODE_DISK_CAPACITY=10000000000
      - NODE_MEMORY_CAPACITY=1000000000
      - LOAD_BALANCING_ALGORITHM=ROUND_ROBIN
    volumes:
      - /mictlanx/mictlanx-sn-0:/mictlanx/mictlanx-sn-0
    networks:
      - mictlanx
    depends_on:
      - mictlanx-xolo-0
      - mictlanx-proxy-0
      - mictlanx-rm-0
  mictlanx-summoner-0:
    image: nachocode/mictlanx:summoner
    container_name: mictlanx-summoner-0
    hostname: mictlanx-summoner-0
    ports:
      - 15000:15000
    environment:
      - NODE_ID=mictlanx-summoner-0
      - NODE_PORT=15000
      - IP_ADDRESS=mictlanx-summoner-0
      - SERVER_IP_ADDRESS=0.0.0.0
      - XOLO_IP_ADDR=mictlanx-xolo-0
      - XOLO_PORT=10000
    volumes:
      - /mictlanx/mictlanx-summoner-0:/mictlanx/mictlanx-summoner-0
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mictlanx
    depends_on:
      - mictlanx-xolo-0
      - mictlanx-proxy-0
      - mictlanx-rm-0

     
networks:
  mictlanx:
    external: true


  


