version: "3.8"
services:

  mictlanx-router-0:

      image: nachocode/mictlanx:router

      container_name:  mictlanx-router-0

      ports:
        - 60666:60666

      environment:
        - LOGGER_NAME=mictlanx-router-0
        - LOG_PATH=/log
        - TEZCANALYTICX_FLUSH_TIMEOUT=10s
        - TEZCANALYTICX_BUFFER_SIZE=100
        - TEZCANALYTICX_PATH=/api/v4/events
        - TEZCANALYTICX_PORT=45000
        - TEZCANALYTICX_HOSTNAME=tezcanalyticx-0
        - TEZCANALYTICX_LEVEL=0
        - TEZCANALYTICX_PROTOCOL=http
        - TEZCANALYTICX_ENABLE=0
        - MICTLANX_PEERS=mictlanx-peer-0:mictlanx-peer-0:7000 mictlanx-peer-1:mictlanx-peer-1:7001
        - MICTLANX_PROCOTOL=http
        - MICTLANX_API_VERSION=4
        - MICTLANX_PEER_HEALER_HEARTBEAT=30sec
        - MICTLANX_GC_HEARTBEAT=60sec

      volumes:
        - /mictlanx/mictlanx-router-0/log:/log

      networks:
        - mictlanx

      restart: unless-stopped

      depends_on:
        - mictlanx-peer-0
        - mictlanx-peer-1

      command: 
        uvicorn mictlanxrouter.server:app --host ${MICTLANX_ROUTER_HOST-0.0.0.0} --port ${MICTLANX_ROUTER_PORT-60666}

  mictlanx-peer-0:
    image: nachocode/mictlanx:peer
    container_name: mictlanx-peer-0
    hostname: mictlanx-peer-0
    privileged: true
    ports:
      - 7000:7000
    environment:
      - USER_ID=6666
      - GROUP_ID=6666
      - BIN_NAME=peer
      - NODE_ID=mictlanx-peer-0
      - NODE_PORT=7000
      - IP_ADDRESS=mictlanx-peer-0
      - SERVER_IP_ADDR=0.0.0.0
      - XOLO_IP_ADDR=mictlanx-xolo-0
      - XOLO_PORT=10000
      - NODE_DISK_CAPACITY=10000000000
      - NODE_MEMORY_CAPACITY=1000000000
      - BASE_PATH=/mictlanx
      - LOCAL_PATH=/mictlanx/local
      - DATA_PATH=/mictlanx/data
      - LOG_PATH=/mictlanx/log
    volumes:
      - /mictlanx/mictlanx-peer-0/log:/mictlanx/log
      - /mictlanx/mictlanx-peer-0/local:/mictlanx/local
      - /mictlanx/mictlanx-peer-0/data:/mictlanx/data
    networks:
      - mictlanx
  mictlanx-peer-1:
    image: nachocode/mictlanx:peer
    container_name: mictlanx-peer-1
    hostname: mictlanx-peer-1
    privileged: true
    ports:
      - 7001:7001
    environment:
      - USER_ID=6666
      - GROUP_ID=6666
      - BIN_NAME=peer
      - NODE_ID=mictlanx-peer-1
      - NODE_PORT=7001
      - IP_ADDRESS=mictlanx-peer-1
      - SERVER_IP_ADDR=0.0.0.0
      - XOLO_IP_ADDR=mictlanx-xolo-0
      - XOLO_PORT=10000
      - NODE_DISK_CAPACITY=10000000000
      - NODE_MEMORY_CAPACITY=1000000000
      - PEERS=mictlanx-peer-0:7000
      - BASE_PATH=/mictlanx
      - LOCAL_PATH=/mictlanx/local
      - DATA_PATH=/mictlanx/data
      - LOG_PATH=/mictlanx/log
    volumes:
      - /mictlanx/mictlanx-peer-1/log:/mictlanx/log
      - /mictlanx/mictlanx-peer-1/local:/mictlanx/local
      - /mictlanx/mictlanx-peer-1/data:/mictlanx/data
    networks:
      - mictlanx
  mictlanx-summoner-0:
      image: nachocode/mictlanx:summoner
      container_name: mictlanx-summoner-0
      hostname: mictlanx-summoner-0
      ports:
        - 15000:15000
      environment:
        - USER_ID=6666
        - GROUP_ID=6666
        - DOCKER_GID=6667
        - BIN_NAME=summoner 
        - BASE_PATH=/mictlanx
        - LOCAL_PATH=/mictlanx/local
        - DATA_PATH=/mictlanx/data
        - LOG_PATH=/mictlanx/log
        - NODE_ID=mictlanx-summoner-0
        - NODE_PORT=15000
        - IP_ADDRESS=mictlanx-summoner-0
        - SERVER_IP_ADDRESS=0.0.0.0
        - XOLO_IP_ADDR=mictlanx-xolo-0
        - XOLO_PORT=10000
        - XOLO_ENABLE=false
      volumes:
        - /mictlanx/mictlanx-summoner-0/local:/mictlanx/local
        - /mictlanx/mictlanx-summoner-0/log:/mictlanx/log
        - /mictlanx/mictlanx-summoner-0/data:/mictlanx/data
        - /var/run/docker.sock:/var/run/docker.sock
      networks:
        - mictlanx
    # depends_on:
      # - mictlanx-xolo-0
      # - mictlanx-proxy-0
      # - mictlanx-rm-0
     
networks:
  mictlanx:
    external: true


  


